# version: '3.9'
# services:
#   db:
#     image: 'mcr.microsoft.com/mssql/server:2019-latest'
#     ports:
#       - 1433:1433
#     environment:
#       SA_PASSWORD: 'Password123'
#       ACCEPT_EULA: 'Y'
#     volumes:
#       - sqlvolume:/var/opt/mssql

# volumes:
#   sqlvolume:

version: '3.8'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local